on: [push]

jobs:
  check-clean-style:
    name: Deploy to gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: install & build
        shell: bash
        run: |
          yarn install --network-concurrency 1
          cp public/config/gh-pages.js public/config/local.js
          yarn build
